id: P214EE55A
initial_creation_type: input
source_metadata:
  title: Bodhicaryāvatāra Series
  language: es
  description: 'Lotsawa House presents the following texts as part of its Bodhicaryāvatāra
    Series:'
  volume:
    9794433614194772b552684900c7ee3a:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    22a87bad4de94e039f29c4d804ccf2d5:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root text
    528012c70752417abd351d008637585c:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    ad696c2f18344442a5084fb0f48c23d3:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Commentaries
    9c1160c15d114547b04fd0491095f2ac:
      title: Overview of the Bodhicaryāvatāra
      parent: Commentaries
    213f6dfe6a6041268d6970b9a0167664:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Commentaries
    f80c94bc301e4285a0eed7a12b29cb9a:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Commentaries
    d0cf368ce2bb4b1c845ba904c12cf50c:
      title: Bodhicaryāvatāra Lineage Prayer
      parent: Lineage Prayers
    23eb7e8e3c3a42ee81fe4f3a25c51592:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Lineage Prayers
    4b4529bb72f34c48869b63b9b4e45105:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      parent: Lineage Prayers
created_at: '2022-03-01T03:02:08.556039'
last_modified_at: '2022-03-01T03:02:08.556041'
